package com.kazemi.EmployeeActivities.Model.Enums;

/**
 * @author fh.kazemi
 **/
public enum ActivityType {
    NORMAL,
    LEAVE,
    LEAVE_MORNING,
    LEAVE_AFTERNOON,
    LEAVE_REQUEST,
    LEAVE_REQUEST_MORNING,
    LEAVE_REQUEST_AFTERNOON,
    ONSITE_CLIENT_MEETING,
    ONSITE_CLIENT_MEETING_MORNING,
    ONSITE_CLIENT_MEETING_AFTERNOON,
    ONLINE_CLIENT_TRAINING,
    ONLINE_CLIENT_TRAINING_MORNING,
    ONLINE_CLIENT_TRAINING_AFTERNOON,
    BUSINESS_TRIP,
    BUSINESS_TRIP_MORNING,
    BUSINESS_TRIP_AFTERNOON,
    UNI,
    UNI_MORNING,
    UNI_AFTERNOON,
    VACATION,
    SCHOOL_HOLIDAY,
    HOME_OFFICE,
    HOME_OFFICE_LEAVE_MORNING,
    HOME_OFFICE_LEAVE_AFTERNOON,
    HOME_OFFICE_ONLINE_CLIENT_TRAINING_MORNING,
    HOME_OFFICE_ONLINE_CLIENT_TRAINING_AFTERNOON,
    HOME_OFFICE_UNI_MORNING,
    HOME_OFFICE_UNI_AFTERNOON
}
